Allowing decompression prevention
metaplex-foundation/mpl-bubblegum pull request #32
Opened 2023-08-24 20:39 UTC by blockiosaurus

This PR aims to allow tree creators to manage whether or not a tree is decompressable. This is helpful to prevent heterogenous collections for protocols that can't handle both cNFTs and NFTs. This is accomplished through the following means:

- A `SetDecompressionPermission` Instruction has been added to toggle whether or not decompression is allowed.
- A new field on the `TreeConfig` called decompression which indicates whether or not it is allowed.
  - All old Trees will be decompressable as they were before.
  - All new trees will **not** be decompressable so the decision to decompression will have to be explicit.
- A `DecompressionPermission` enum that provides a human readable description of whether or not it is enabled.
- A `create_tree_v2` instruction that will require all created trees to explicitly be labeled as decompressable or not.
- Deprecation of the `create_tree` instruction to indicate the above change.

2023-08-25 21:04 UTC, danenbm requested changes

2023-08-25 21:04 UTC, danenbm commented on programs/bubblegum/program/tests/decompression.rs
Nice!  and thank you for splitting this out to a new file as well.

2023-08-25 21:04 UTC, danenbm commented on clients/js/src/generated/accounts/treeConfig.ts
Did you have a JS test to add for this feature?  I'm not saying we need one, but I thought you mentioned offline that you were writing one, so wanted to make sure it was included if you had written it.

2023-08-25 21:51 UTC, blockiosaurus commented on clients/js/src/generated/accounts/treeConfig.ts
Eh, I think the Umi library is pretty complete, so we can always hold off until someone asks for it.

2023-08-25 21:52 UTC, blockiosaurus commented on clients/js/src/generated/accounts/treeConfig.ts
I did not, I was just trying to fix the tests I broke for the redeem and decompress JS tests. Lemme commit those changes.

2023-08-25 21:52 UTC, blockiosaurus commented on yarn.lock
Whoops!

2023-08-28 15:47 UTC, danenbm commented on clients/js/src/generated/accounts/treeConfig.ts
ok per offline discussion, our plan will be for short term we will still regenerate it.

And then we come up with the metric for deciding most people are using now using Umi, to decide when to actually delete JS Solita.

2023-08-28 15:48 UTC, danenbm submitted a review, later dismissed
Code change looks great!

Per offline discussion, our plan will be for short term we will still regenerate JS Solita but in a follow on PR since its not properly setup right now.

And then we come up with the metric for deciding most people are using now using Umi, to decide when to actually delete JS Solita.

2023-08-28 19:04 UTC, febo approved these changes

2023-08-28 20:49 UTC, danenbm approved these changes

2023-08-28 22:37 UTC, merged